# -*- coding: utf-8 -*-
"""baekjoon_l0816_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ky1tkwANXjomsRc4lj33jfvvxU6gfpgR
"""

num1 = int(input())
arr1 = list(map(int, input().split()))

dict1 = {}
for i in arr1:
    if i in dict1:
        dict1[i] += 1
    else:
        dict1[i] = 1

num2 = int(input())
arr2 = list(map(int, input().split()))
for i in arr2:
    if i in dict1:
        print(dict1[i], end= ' ')
    else:
        print(0, end = ' ')