# -*- coding: utf-8 -*-
"""baekjoon_10818.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10xDz_XDx1OIf8oM3GCCP5rXj-q0EQGrP
"""

num = int(input())
ls = input().split()
max = -1000000
min = 1000000

for i in range(num):
    if int(ls[i]) > max:
        max = int(ls[i])
    else:
        pass
    if int(ls[i]) < min:
        min = int(ls[i])
    else:
        pass
print(min, max)