# -*- coding: utf-8 -*-
"""baekjoon_11652.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148cu-Mqs0lu9QiqasRrCEax8ie8UlrIc
"""

import sys
num = int(sys.stdin.readline())
ls = []
dic = {}
for _ in range(num):
    x = sys.stdin.readline()
    ls.append(x)
    if x in dic.keys():
        dic[x] += 1
    else:
        dic[x] = 1
keys = list(set(ls))
max = 0
dap = 0
for k in keys:
    if max < dic[k]:
        max = dic[k]
        dap = int(k)
    elif max == dic[k]:
        if dap < int(k):
            pass
        elif dap > int(k):
            dap = int(k)
    else:
        pass
print(dap)