# -*- coding: utf-8 -*-
"""baekjoon_11728.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0rSwHQ8VqVBTl51VFLE9TThF4bYHsTZ
"""

n1, n2 = map(int, input().split())
ls = []
for i in [n1,n2]:
    var = map(int, input().split())
    for k in var:
        ls.append(k)
ls.sort()
for j in range(len(ls)):
    print(ls[j], end=' ')