# -*- coding: utf-8 -*-
"""baekjoon_1302.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzcgO5zKMAPz5Xw-xjGmVbZAjN2Y9lRI
"""

from collections import Counter
num = int(input())
ls = [input() for _ in range(num)]
cnt = Counter(ls)
tar = cnt.most_common()
tar.sort(key = lambda x: (-x[1],x[0]))
print(str(tar[0][0]))