# -*- coding: utf-8 -*-
"""baekjoon_1431.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RK9f1Trtv1doX-2fb4FO_-6dUSN99r_x
"""

num = int(input())
lss = []

for i in range(num):
    lss.append(input())

lss.sort(key = lambda x : (len(x), sum(int(a) for a in x if a.isdigit()), x))

for g in lss:
    print(g)