# -*- coding: utf-8 -*-
"""baekjoon_1654.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mXMz2csUd_GJP0oa3D3Xzf_Sg-ixSC0W
"""

num, nth = map(int, input().split())
result = []
ls = [int(input()) for _ in range(num)]
left, right = 1, max(ls)
while left <= right:
    mid = (left + right) // 2 
    lines = 0
    for i in ls:
        lines += i // mid
        
    if lines >= nth:
        left = mid + 1
    else:
        right = mid - 1
print(right)