# -*- coding: utf-8 -*-
"""baekjoon_2075.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_FTZvWvuJxpNL5J0956GiFbkYjsgCYo
"""

import sys, heapq
num = int(sys.stdin.readline())
heap = []
for i in range(num):
    x = list(map(int, sys.stdin.readline().split()))
    if len(heap) < num:
        heap = x
    else:
        for k in x:
            if heap[0] < k:
                heapq.heappop(heap)
                heapq.heappush(heap,k)
print(heap[0])