# -*- coding: utf-8 -*-
"""baekjoon_2675.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vSRmYdJ7aekKNmX_9DlNXDFtBIXXSEDq
"""

num = int(input())
for _ in range(num):
    x, y = input().split()
    ls = []
    result = ''
    for i in range(len(y)):
        ls.append(y[i])
        result += ls[i] * int(x)
    print(result)