# -*- coding: utf-8 -*-
"""baekjoon_2750.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hrYbyLo4JV1eBc-EnOYHs2c4OcI-rayr
"""

num = int(input())
ls = [0]*num
result = [0]*num
for i in range(num):
    ls[i] = int(input())
    if i == 0:
        pass
ls.sort()
for i in range(num):
    print(ls[i])