# -*- coding: utf-8 -*-
"""baekjoon_2752.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDCr7qIq0vS3b2fKVu32ldIv3PQABtx6
"""

ls = input().split()
for t in range(3):
    ls[t] = int(ls[t])
for i in range(2):
    for k in range(2):
        if ls[k] > ls[k+1]:
            x = ls[k]
            y = ls[k+1]
            ls[k+1] = x
            ls[k] = y
result = ''
for j in range(3):
    result += str(ls[j]) + ' '
print(result)