# -*- coding: utf-8 -*-
"""baekjoon_2822.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19hn91nSJ5uGj0KK6tLz9V2Hh7wDwcwfY
"""

ls = []
sum = 0
result = []
for k in range(8):
    x = int(input())
    ls.append([x,k+1])
ls.sort(key = lambda x : -x[0])
for i in range(5):
    sum += ls[i][0]
    result.append(ls[i][1])
print(sum)
result.sort()
for i in range(5):
    print(result[i],end=' ')