# -*- coding: utf-8 -*-
"""baekjoon_5063.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIQDGw0ZtSQ87ls5XUcF-rP0N77WPyJL
"""

num = int(input())
for _ in range(num):
    a, b, c  = map(int, input().split())
    if b - c > a:
        print('advertise')
    elif b - c == a:
        print('does not matter')
    else:
        print('do not advertise')